### ISSUE TITLE
Edit Service Provider> Address doesn't update

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#12]
Steps to reproduce:

1) Create appointment.
2) Edit appointment.
3) Change service provider.

Result: On the drive detail's screen, the name of the service provider will change, but the address won't. 

![image](https://user-images.githubusercontent.com/24197365/75636539-27b47e00-5be5-11ea-8b07-48e981a77c64.png)

**Comment by emilyfreas** [comment]
Cannot recreate this issue. Was closed back in mid-March, but reopened, and I missed last weeks call, so not sure why it was reopened. Scheduling appointments via the web app and my phone don't recreate the issue. Seems to be solved.
