### ISSUE TITLE
Horizontal Scroll Bug

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#15]
There's a weird issue with the horizontal scroller where it will skip weeks or overlap dates. Here's one example I could reproduce, but there are others. 

![image](https://user-images.githubusercontent.com/24197365/75637797-2471c000-5bee-11ea-9a83-0c059d6a0430.png)

**Comment by emilyfreas** [comment]
Been testing this today and am struggling. When I log in and view "my drives" I see two March 8ths and can't scroll past March 13th. Going to restart chrome and other applications to see what I see, but wanted to note this before I did. 
![Screen Shot 2020-03-11 at 1 47 16 PM](https://user-images.githubusercontent.com/61757990/76452291-e3706d00-639e-11ea-9666-cfdff73d448a.png)

**Comment by kilo1sierra** [comment]
working fine for me in Chrome / iphone.

**Comment by Katieesq** [comment]
Confirmed, Moving to done for 3/14 release.
