### ISSUE TITLE
Dispatcher - "Deny" backend

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#20]
Create endpoint to allow dispatcher to retract a driver's application before the application has been approved. This endpoint should change the DriveLogStatusID to 4 and IsActive to False in the Volunteer_DriveLog table.

**Comment by Katieesq** [comment]
Does not appear that this code is currently on test. Moving back to "In Development."

**Comment by kilo1sierra** [comment]
this appears to be working based on my testing.
