### ISSUE TITLE
Update drive card wording 

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#26]
Per dispatcher feedback and discussion, we want to update the wording on drive cards to better communicate the direction of the drive. 

If the service provider is a clinic, change language to say "To Clinic" and "From Clinic."
If the service provider is a courthouse, change language to say, "To Courthouse" and "From Courthouse."
If the service provider is lodging, change language to say, "To Lodging" and "From Lodging."

![image](https://user-images.githubusercontent.com/24197365/75947629-a8ce7800-5e66-11ea-811c-72b5f3d7b7ea.png)

**Comment by Katieesq** [comment]
Hmm - it looks like the wording on the "My Drives" page and the wording on the main schedule is different. Let's stick with the wording that's on the main schedule for brevity's sake. Moving back to "In Development."

![image](https://user-images.githubusercontent.com/24197365/80290855-0c11b380-870e-11ea-8a0c-bb7b57cb7c96.png)

**Comment by Katieesq** [comment]
Hmm - it looks like this code might not have been pushed to test. I'm still seeing the incorrect wording on the "My Drives" screen. Moving back to "In Development."

**Comment by ahollyer** [comment]
Sorry about that! Didn't notice the additional comment @Katieesq :) It's fixed now.

**Comment by Katieesq** [comment]
Tested and confirmed that the correct wording appears on My drives and schedule view. Moving to Ready to Release.
