### ISSUE TITLE
SMS> Confirmed drive> One way drive from clinic confirmation is confusing

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#28]
We've had several reports from drivers who are confused by our confirmation texts when they are only taking a drive from a service provider. This is because the text message contains the date and time of the appointment, which is much earlier than the drive from pickup time. See screenshot below for confusion details.

![image](https://user-images.githubusercontent.com/24197365/76227830-e4ae6800-61ed-11ea-94ae-4ad18c1e911a.png)

We need to change the language here so that one way drivers don't get confused. Could the messages consider the appointment duration? Or do we just need to add some language that clarifies it's the "drive from" the service provider?

**Comment by d-m-wilson** [comment]
Implemented in https://github.com/clinicaccess/casn-app/commit/68919f255215082e96c2d69d317505d29431b539

**Comment by Katieesq** [comment]
Tested and confirmed that text messages to dispatchers and drivers all show the correct estimated time stamps for all appointment types when applying/approving drives from a service provider. Moving to Ready for Release.
