### ISSUE TITLE
GET /appointments API omits appointments which occur on the specified endDate

### ISSUE THREAD

**Issue by d-m-wilson** [clinicaccess/casn-app#31]
If endDate does not have a time component, then the default behavior is to use Midnight. For example, if endDate is "2020-03-14" then the backend will interpret that as 12:00:00 AM on March 14th, 2020. This in turn causes any appointments which occur **_on_** the endDate to be omitted from the results.

endDate was intended to be inclusive. When the time part is Midnight, the backend should add 23:59:59. In the example above, endDate would then become 11:59:59 PM on March 14th, 2020 (the end of the day).

**Comment by Katieesq** [comment]
Looking good. Moving to Done for release hopefully 3/14?

**Comment by d-m-wilson** [comment]
Note that this bug also applies to GET /drives/myDrives. I just fixed that with commit 67e7e0683e23372076d729834e4d0853af5a244b
