### ISSUE TITLE
Drive Card> Map View> Weird Highlight

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#35]
When you tap a drive card and tap the map view, a box is highlighted around it.

![image](https://user-images.githubusercontent.com/24197365/76691866-8fbf8700-661d-11ea-939d-23d61b7f9c59.png)

**Comment by ahollyer** [comment]
Hmm for some reason I didn't see this before. @Katieesq Are you referring to the focus box on the right arrow at the bottom of the page, or is this the wrong screenshot?

**Comment by Katieesq** [comment]
This is no longer reproducible, so we are going to close this for now.
