### ISSUE TITLE
Status> Rideshare

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#46]
We need a status to indicate when the caller has opted to use a rideshare for one or both of their drives. 

This status should mark the drive status as approved, rather than cancelled, since staffing via rideshare is a desirable outcome. 

We can stuff this feature just about anywhere we can fit it on the dispatcher view for now, and fix it later.

**Comment by Katieesq** [comment]
Moving back to "In Development" so @ahollyer can implement front end.

**Comment by emilyfreas** [comment]
Notes from the initial testing pass (to discuss at the meeting tonight) below. More testing/round two after some discussion tonight is possible/likely. 

Test rides: 1986a - e
1986c&d: editing appointment to add "to" drive - submit stops working, the back button still works
1986b (from) & 1986a (to): after driver approved canceling to rideshare no longer works. you can remove the approved driver and then cancel to rideshare. Uncertain if this is a feature or a bug
1986e - can cancel to rideshare before approving drivers
1986f - cannot edit to add "to" drive once created. Can cancel while driver application pending without denying
