### ISSUE TITLE
Edit Appointment> Remove "Drive To"> 504 errors

### ISSUE THREAD

**Issue by Katieesq** [clinicaccess/casn-app#48]
Steps to reproduce this bug.

1. Create a round trip appointment of any type.
2. Edit the appointment so that the appointment no longer has a "drive to" leg of the trip.

Result: 504 error appear in the console. It does appear that the appointment does save correctly, however.
![image](https://user-images.githubusercontent.com/24197365/81522274-9a418880-930f-11ea-8f18-873ef5b68905.png)

**Comment by d-m-wilson** [comment]
FYI, while fixing this one, I noticed that the same issue would have happened when editing an appointment to remove a "drive from".

**Comment by Katieesq** [comment]
Tested and confirmed that this issue is resolved. Also retested all items that are currently listed and "Ready to Release." Moving to Ready to Release.
